hydra:
  run:
    dir: ../predicts/${now:%Y-%m-%d-%H-%M-%S}
model:
  
  path: /export1/project/zihao/outputs/2022-04-16-14-21-43/ckpts/epoch197.pt
  ffm:
    mode: linear
    L: 10
    num_input: 3
  mlp:
    num_inputs: 60
    num_outputs: 3
    num_neurons: 256
    depth: 16
    skip_list: [2,5,8,11,14]
    body_acti: LeakyReLU
    last_acti: Null
  nerf:
    type: GIFNERF
  batch_size: 8000
  GPUIndex: [0]
gif:
  data_path: data/rocket.gif
  ofargs: [0.5, 3, 15, 3, 5, 1.2, 0]
  split: 3
  name: 'rocket_slow_mo'
  slowmo_factor: 10

